version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: montly
    versioning-strategy: increase
    open-pull-requests-limit: 1
    labels:
      - 'pr: dependencies'
